### ISSUE TITLE
not written in rust 🚀 

### ISSUE THREAD

**Issue by Realswitzer** [binex-dsk/clink#1]
why would you not use rust 🚀 with its blazing fast 🚀 speeds that are way better than c and small file size 🚀 and less vulnerabilities 🚀 
as it is rust 🚀 it is impossible to have vulnerabilities 🚀 and it is much faster program wise 🚀 and programming wise 🚀 because you can quickly 🚀 type everything due to the power of rust 🚀 
for a web interface rust 🚀 is obviously the best choice 🚀 
it also uses minimal resources 🚀 which helps with its performance 🚀 which already beats the competition

**Comment by binex-dsk** [comment]
feature
